FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-amd64 AS build
WORKDIR /src
COPY ["ShellyToHomie/ShellyToHomie.csproj", "ShellyToHomie/"]
RUN dotnet restore "ShellyToHomie/ShellyToHomie.csproj"
COPY . .
WORKDIR "/src/ShellyToHomie"

RUN dotnet build "ShellyToHomie.csproj" -c Release -o /app/build

ARG VERSION_SUFFIX
FROM build AS publish

RUN dotnet publish "ShellyToHomie.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ShellyToHomie.dll"]
